server:
  port: 8100

spring:
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: WORKTALK_JPA
    password: hi123456

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100

  thymeleaf:
    view-names: thymeleaf/*
    prefix: classpath:/templates/
    suffix: .html
    cache: false
    check-template-location: true

logging:
  level:
    org.hibernate.SQL: debug
#    org.hibernate.type: trace
